export const deliveries = [
  {
    name: "Katie Bell",
    isVIP: true,
    peopleCount: "2",
    paymentMethod: "cash",
    amount: "$62.50",
    OverDue: true,
    timeRemaining: 12,
    type: "table",
    chipTitle: "Table 32",
    isSelected: false,
    company: {
      title: "RESY",
      bgColor: "bg-gray-light",
      color: "text-orange-dark1",
    },
  },
  {
    name: "Cho Chang",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$73.25",
    OverDue: false,
    timeRemaining: 2,
    type: "delivery",
    chipTitle: "Delivery #5623",
    isSelected: false,
    company: {
      title: "-",
      bgColor: "bg-cyan-dark",
      color: "text-white",
    },
  },
  {
    name: "Johnny Appleseed",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$105.10",
    OverDue: false,
    timeRemaining: 10,
    type: "delivery",
    chipTitle: "Delivery #4302",
    isSelected: true,
    company: {
      title: "Web",
      bgColor: "bg-gray-light",
      color: "text-gray-dark",
    },
  },
  {
    name: "Romilda Vane",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$94.60",
    OverDue: false,
    timeRemaining: 13,
    type: "pickup",
    chipTitle: "Pickup #6452",
    isSelected: false,
    company: {
      title: "Uber",
      bgColor: "bg-black",
      color: "text-white",
    },
  },
  {
    name: "Lee Jordan",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$24.40",
    OverDue: false,
    timeRemaining: 22,
    type: "delivery",
    chipTitle: "Delivery #9830",
    isSelected: false,
    company: {
      title: "-",
      bgColor: "bg-orange-dark2",
      color: "text-white",
    },
  },
];
