export const deliveries = [
  {
    name: "Katie Bell",
    isVIP: true,
    peopleCount: "2",
    paymentMethod: "cash",
    amount: "$62.50",
    OverDue: true,
    timeRemaining: 12,
    type: "table",
    chipTitle: "Table 32",
    isSelected: false,
  },
  {
    name: "Cho Chang",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$73.25",
    OverDue: false,
    timeRemaining: 2,
    type: "delivery",
    chipTitle: "Delivery #5623",
    isSelected: false,
  },
  {
    name: "Johnny Appleseed",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$105.10",
    OverDue: false,
    timeRemaining: 10,
    type: "delivery",
    chipTitle: "Delivery #4302",
    isSelected: true,
  },
  {
    name: "Romilda Vane",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$94.60",
    OverDue: false,
    timeRemaining: 13,
    type: "pickup",
    chipTitle: "Pickup #6452",
    isSelected: false,
  },
  {
    name: "Lee Jordan",
    isVIP: false,
    peopleCount: "0",
    paymentMethod: "card",
    amount: "$24.40",
    OverDue: false,
    timeRemaining: 22,
    type: "delivery",
    chipTitle: "Delivery #9830",
    isSelected: false,
  },
];
